gajdaw-teaching/cw-01-wiersze

mrugala/wiersz.txt
=> dodaj wiersz

edgar-karapetyan/Annabel Lee.txt
It was many and many a year ago,
In a kingdom by the sea,
That a maiden there lived whom you may know
By the name of Annabel Lee;
And this maiden she lived with no other thought
Than to love and be loved by me.
I was a child and she was a child,
In this kingdom by the sea,
But we loved with a love that was more than love—
I and my Annabel Lee—
With a love that the wingèd seraphs of Heaven
Coveted her and me.
And this was the reason that, long ago,
In this kingdom by the sea,
A wind blew out of a cloud, chilling
My beautiful Annabel Lee;
So that her highborn kinsmen came
And bore her away from me,
To shut her up in a sepulchre
In this kingdom by the sea.
The angels, not half so happy in Heaven,
Went envying her and me—
Yes!—that was the reason (as all men know,
In this kingdom by the sea) …
=> Annabel Lee

miloszkulesza/tuwim/calujta-mnie-w-dupe.txt, miloszkulesza/tuwim/do-krytykow.txt, miloszkulesza/tuwim/do-prostego-czlowieka.txt, miloszkulesza/tuwim/moj-dzionek.txt, miloszkulesza/tuwim/wiosna.txt
Miłosz Kulesza milosz.kulesza1@gmail.com
=> Miłosz Kulesza milosz.kulesza1@gmail.com

kacper-stoczkowski/samolyk/codziennie.txt.txt
=> [Janek Smolyk] Codziennie

kacper-stoczkowski/samolyk/na-prezent.txt.txt
=> [Janek Smolyk] Na Prezent

kacper-stoczkowski/samolyk/zdjecia.txt
=> [Janek Smolyk] Zdjecia

kacper-stoczkowski/samolyk/wszy.txt
=> [Janek Smolyk] Wszy

broniewski/bagnet-na-bron.txt
Piotr Sołdrzyński p.soldrz@gmail.com
=> [Władysław Broniewski] Bagnet na Broń!

broniewski/baudelaire.txt
Piotr Sołdrzyński - p.soldrz@gmail.com
=> [Władysław Broniewski] Baudelaire

lermontov/the-sail.txt
=> a new poem

wojtekfolder/loremipsumWojtek.txt
=> loremipsumWojtek

lermontov/a-dream.txt, lermontov/i-go-out-on-the-road-alone.txt, lermontov/the-leaf.txt
=> lermontov poems

kryst/poem.txt, kryst/secondpoem.txt
=> First commit with two poems

kryst/kaczmarski.txt
=> Another pull request

MatGor/Switezianka.txt
Feat: Add new poem Świtezianka
=> [Adam Mickiewicz] Świtezianka

MatGor/Switezianka.txt
Change coding to UTF-8 and change name of pull request
=> Feat:[Adam Mickiewicza]Świtezianka

boleslaw-lesmian/ogrod-zaklety.txt
=> Boleslaw lesmian

madison-thomps/the-man-behind-the-mask.txt
=> feat:[madison-thomps] The man behind the mask

bez-ciebie/maria-pawlikowska-jasnorzewska.txt, jan-brzechwa/zoo.txt
=> feat: [Maria Pawlikowska-Jasnorzewska] Bez ciebie

wierszkryst/wiersztuwim.txt
=> Adding poem

Do_Gospodyni/do_gospodyni.txt
=> Praca Domowa
